# Generated by Django 4.2.3 on 2023-07-19 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ManyToManyField(related_name='news', to='core.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='news',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='news', to='core.origin', verbose_name='Источник'),
        ),
    ]
