# Generated by Django 4.2.3 on 2023-07-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_news_options_alter_news_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='likes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
