# Generated by Django 4.2.3 on 2023-07-28 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_news_options_alter_origin_options'),
    ]

    operations = [
    ]
